---
- name: assert | Test keepalived_global_defs if defined
  ansible.builtin.assert:
    that:
      - keepalived_global_defs is defined
      - keepalived_global_defs is mapping
      - keepalived_global_defs.enable_script_security is undefined or keepalived_global_defs.enable_script_security is boolean
      - keepalived_global_defs.script_user is undefined or keepalived_global_defs.script_user is string
    quiet: true
  when: keepalived_global_defs is defined

- name: assert | Test keepalived_vrrp_instances
  ansible.builtin.assert:
    that:
      - keepalived_vrrp_instances is defined
      - keepalived_vrrp_instances is iterable
    quiet: true

- name: assert | Test item in keepalived_vrrp_instances
  ansible.builtin.assert:
    that:
      - item.name is defined
      - item.name is string
      - item.name is not none
      - item.state is defined
      - item.state is string
      - item.state in [ "BACKUP", "MASTER" ]
      - item.interface is defined
      - item.interface is string
      - item.interface is not none
      - item.virtual_router_id is defined
      - item.virtual_router_id is number
      - item.virtual_router_id >= 0
      - item.virtual_router_id <= 255
      - item.priority is defined
      - item.priority is number
      - item.priority >= 1
      - item.priority <= 255
      - item.notify_master is undefined or item.notify_master is string
      - item.notify_backup is undefined or item.notify_backup is string
      - item.notify_stop is undefined or item.notify_stop is string
    quiet: true
  loop: "{{ keepalived_vrrp_instances }}"
  loop_control:
    label: "{{ item.name }}"

- name: assert | Loop over keepalived_vrrp_instances
  ansible.builtin.include_tasks:
    file: assert_instances.yml
  loop: "{{ keepalived_vrrp_instances }}"
  loop_control:
    label: "{{ instance.name }}"
    loop_var: instance
